Switch to monorepo layout
ilios/lti-dashboard pull request #1481
Opened 2024-02-10 00:24 UTC by jrjohnson

In preparation for moving the entire application into the frontend.

2024-02-10 00:33 UTC, jrjohnson commented
Netlify will get fixed up after we merge.

2024-02-10 02:30 UTC, stopfstedt requested changes
the `/dist` directory got added by accident. pls remove, thanks.

2024-02-12 04:05 UTC, jrjohnson commented
Great catch. Fixed.

2024-02-12 16:20 UTC, stopfstedt approved these changes

2024-02-12 16:47 UTC, merged